import { categoryTotals, filterPeriod, fuelComparison, fuelSummary, monthlyTotals, tripDistance } from "./calculations.js";
import { financialEvents, getFinanceSummary } from "./reports.js";
import { decimal, escapeHtml, formatDate, money } from "./utils.js";

const titles = { dashboard: "Dashboard", vehicles: "Veículos", refuels: "Abastecimentos", maintenances: "Manutenções", tires: "Pneus", expenses: "Despesas", trips: "Viagens", finance: "Financeiro", reports: "Relatórios", sharing: "Compartilhamentos", payments: "Formas de pagamento" };
export const viewTitles = titles;

const metric = (label, value, foot, icon, accent = false) => `<article class="panel metric-card ${accent ? "metric-accent" : ""}"><span class="metric-icon">${icon}</span><p class="metric-label">${escapeHtml(label)}</p><p class="metric-value mono">${escapeHtml(value)}</p><p class="metric-foot">${escapeHtml(foot)}</p></article>`;

function pageIntro(title, text, right = "") {
  return `<div class="page-intro"><div><h2>${escapeHtml(title)}</h2><p>${escapeHtml(text)}</p></div>${right}</div>`;
}

export function renderDashboard({ vehicle, data, events, summary, canEdit }) {
  if (!vehicle) return renderNoVehicle();
  const currentKm = Math.max(Number(vehicle.currentOdometer) || 0, ...data.refuels.map((item) => Number(item.odometer) || 0), ...data.maintenances.map((item) => Number(item.odometer) || 0), ...data.tires.map((item) => Number(item.odometer) || 0));
  const monthly = monthlyTotals(events, "date", "amount", 6);
  const highest = Math.max(1, ...monthly.map((item) => item.value));
  const categories = categoryTotals(events, "category", "amount").slice(0, 5);
  const categoryMax = Math.max(1, ...categories.map((item) => item.value));
  const recent = events.slice(0, 5);
  const comparison = fuelComparison(data.refuels).slice(0, 3);
  const alerts = (data.maintenances || []).filter((item) => item.nextDate || item.nextOdometer).filter((item) => {
    const dateSoon = item.nextDate && new Date(`${item.nextDate}T12:00:00`) <= new Date(Date.now() + 30 * 86400000);
    const kmSoon = item.nextOdometer && Number(item.nextOdometer) - currentKm <= 1000;
    return dateSoon || kmSoon;
  }).slice(0, 3);
  const consumption = summary.fuelData.averageKmPerLiter ? `${decimal(summary.fuelData.averageKmPerLiter)} km/L` : "Aguardando dados";
  return `
    <section class="welcome-band"><div class="welcome-copy"><p class="section-kicker">RESUMO DO SEU VEÍCULO</p><h2>${escapeHtml(vehicle.name)}</h2><p>${escapeHtml([vehicle.year, vehicle.make, vehicle.model, vehicle.version].filter(Boolean).join(" · ") || "Registre o uso do veículo para acompanhar seus indicadores.")}</p><div class="quick-actions">${canEdit ? `<button class="button button-primary" data-new-kind="refuels">＋ Abastecimento</button><button class="button button-ghost" data-new-kind="maintenances">＋ Manutenção</button><button class="button button-ghost" data-new-kind="expenses">＋ Despesa</button><button class="button button-ghost" data-new-kind="trips">＋ Viagem</button>` : `<span class="tag">Acesso de visualização</span>`}</div></div><div class="welcome-number"><span>Quilometragem registrada</span><strong>${escapeHtml(currentKm.toLocaleString("pt-BR"))} km</strong></div></section>
    <section class="grid grid-4">
      ${metric("Gasto neste mês", money(events.filter((item) => (item.date || "").startsWith(new Date().toISOString().slice(0, 7))).reduce((sum, item) => sum + item.amount, 0)), "Veículo selecionado", "↗", true)}
      ${metric("Combustível", money(summary.fuel), `${data.refuels.length} abastecimentos`, "◉")}
      ${metric("Manutenção + pneus", money(summary.maintenance + summary.tires), `${data.maintenances.length + data.tires.length} registros`, "⚙")}
      ${metric("Consumo médio", consumption, summary.fuelData.intervals.length ? `${summary.fuelData.intervals.length} intervalos válidos` : "Consumo ainda não disponível", "⌁")}
    </section>
    <section class="dashboard-grid">
      <article class="panel chart-panel"><div class="panel-head"><div><h3>Gastos ao longo do tempo</h3><p>Últimos seis meses · todos os tipos de registro</p></div><div class="chart-legend"><span><i class="legend-dot"></i> Total</span></div></div><div class="panel-body"><div class="bar-chart">${monthly.map((item) => `<div class="bar-column"><span class="bar-value">${item.value ? money(item.value).replace(",00", "") : ""}</span><div class="bar-stack"><div class="bar-fill" style="height:${Math.max(2, item.value / highest * 100)}%"></div></div><span class="bar-label">${escapeHtml(item.label)}</span></div>`).join("")}</div></div></article>
      <article class="panel"><div class="panel-head"><div><h3>Onde o dinheiro vai</h3><p>Despesas registradas</p></div></div><div class="panel-body">${categories.length ? `<div class="category-bars">${categories.map((item) => `<div class="category-row"><span class="category-name">${escapeHtml(item.category)}</span><div class="category-track"><div class="category-fill" style="width:${Math.max(2, item.value / categoryMax * 100)}%"></div></div><span class="category-value">${money(item.value)}</span></div>`).join("")}</div>` : `<div class="chart-empty">Registre um gasto para ver a distribuição.</div>`}</div></article>
    </section>
    <section class="dashboard-grid">
      <article class="panel"><div class="panel-head"><div><h3>Movimentações recentes</h3><p>Últimos registros deste veículo</p></div><button class="section-link" data-view="finance">Ver financeiro →</button></div><div class="panel-body"><div class="activity-list">${recent.length ? recent.map((item) => `<div class="activity-row"><span class="activity-icon">${eventIcon(item.kind)}</span><div class="activity-copy"><strong>${escapeHtml(item.detail)}</strong><span>${escapeHtml(item.category)} · ${formatDate(item.date)}</span></div><span class="activity-value">${money(item.amount)}</span></div>`).join("") : `<div class="table-empty"><strong>Nenhum registro por aqui</strong>Use um atalho acima para começar.</div>`}</div></div></article>
      <div class="stack">
        <article class="panel"><div class="panel-head"><div><h3>Comparação de combustível</h3><p>Custo real por km · abastecimentos completos</p></div></div><div class="panel-body">${comparison.length ? `<div class="fuel-comparison">${comparison.map((item, index) => `<div class="fuel-option ${index === 0 ? "best" : ""}"><div><strong>${escapeHtml(item.fuel)} ${index === 0 ? "· menor custo" : ""}</strong><span>${decimal(item.kmPerLiter)} km/L · ${money(item.pricePerLiter)}/L</span></div><b>${money(item.costPerKm)}/km</b></div>`).join("")}</div><p class="comparison-note" style="margin:12px 0 0">A comparação usa intervalos de tanque cheio com um único combustível. Registre mais abastecimentos para comparar.</p>` : `<div class="chart-empty">Aguardando dados suficientes de tanque cheio.</div>`}</div></article>
        <article class="panel"><div class="panel-head"><div><h3>Próximas manutenções</h3><p>Alertas com base nos seus registros</p></div></div><div class="panel-body">${alerts.length ? `<div class="alert-list">${alerts.map((item) => `<div class="alert-card maintenance-alert"><span class="alert-symbol">◷</span><div><strong>${escapeHtml(item.service || item.category || "Manutenção")}</strong><span>${item.nextOdometer ? `Meta em ${Number(item.nextOdometer).toLocaleString("pt-BR")} km` : ""}${item.nextOdometer && item.nextDate ? " · " : ""}${item.nextDate ? `Até ${formatDate(item.nextDate)}` : ""}</span></div></div>`).join("")}</div>` : `<div class="table-empty">Nenhum alerta próximo.</div>`}</div></article>
      </div>
    </section>`;
}

export function renderNoVehicle() {
  return `<div class="empty-state"><div class="empty-illustration">▰</div><h3>Comece adicionando um veículo</h3><p>Cadastre seu carro, moto ou utilitário. Depois, registre os acontecimentos e deixe o Rota calcular os indicadores para você.</p><button class="button button-primary" data-new-kind="vehicles">＋ Cadastrar veículo</button></div>`;
}

function eventIcon(kind) { return ({ refuels: "◉", maintenances: "⚙", tires: "◌", expenses: "↗" })[kind] || "•"; }

export function renderVehicles(vehicles, currentId, userId, canAdd = true) {
  const cards = vehicles.map((vehicle) => {
    const subtitle = [vehicle.year, vehicle.make, vehicle.model].filter(Boolean).join(" · ") || `${vehicle.type || "Veículo"}`;
    return `<article class="panel vehicle-card"><div class="vehicle-card-top"><span class="vehicle-glyph">▰</span><span class="tag ${vehicle.role === "owner" ? "" : "tag-muted"}">${vehicle.role === "owner" ? "Proprietário" : vehicle.role === "editor" ? "Editor" : "Visualizador"}</span></div><h3>${escapeHtml(vehicle.name)}</h3><p>${escapeHtml(subtitle)}</p><div class="vehicle-card-meta"><span>${Number(vehicle.currentOdometer || 0).toLocaleString("pt-BR")} km informados</span>${vehicle.fuel ? `<span>${escapeHtml(vehicle.fuel)}</span>` : ""}</div><div class="vehicle-card-footer"><span class="record-subtitle">${currentId === vehicle.id ? "Selecionado agora" : "Veículo"}</span><div class="row-actions"><button class="text-button" data-select-vehicle="${escapeHtml(vehicle.id)}">${currentId === vehicle.id ? "Ativo" : "Selecionar"}</button>${vehicle.role === "owner" ? `<button class="row-action" title="Editar veículo" data-edit-vehicle="${escapeHtml(vehicle.id)}">✎</button><button class="row-action" title="Arquivar veículo" data-archive-vehicle="${escapeHtml(vehicle.id)}">⌑</button><button class="row-action danger" title="Excluir veículo e registros" data-delete-vehicle="${escapeHtml(vehicle.id)}">×</button>` : ""}</div></div></article>`;
  }).join("");
  return `${pageIntro("Sua garagem", "Gerencie os veículos e escolha qual acompanhar.", canAdd ? `<button class="button button-primary" data-new-kind="vehicles">＋ Adicionar veículo</button>` : "")}${vehicles.length ? `<div class="view-cards">${cards}</div>` : `<div class="empty-state"><div class="empty-illustration">▰</div><h3>Garagem vazia</h3><p>Adicione seu primeiro veículo para organizar abastecimentos, manutenções e gastos.</p>${canAdd ? `<button class="button button-primary" data-new-kind="vehicles">＋ Cadastrar veículo</button>` : ""}</div>`}`;
}

export function renderPaymentMethods(methods = []) {
  const rows = methods.map((method) => {
    const expiry = String(method.expiry || "").split("-");
    const formattedExpiry = expiry.length === 2 ? `${expiry[1]}/${expiry[0].slice(-2)}` : "\u2014";
    return `<tr><td><strong>${escapeHtml(method.name)}</strong></td><td>${escapeHtml(method.institution)}</td><td>&#8226;&#8226;&#8226;&#8226; ${escapeHtml(method.lastFour)}</td><td>${escapeHtml(formattedExpiry)}</td><td><div class="row-actions"><button class="row-action" title="Editar cart\u00e3o" data-edit-payment-method="${escapeHtml(method.id)}">&#9998;</button><button class="row-action danger" title="Remover cart\u00e3o" data-delete-payment-method="${escapeHtml(method.id)}">&times;</button></div></td></tr>`;
  }).join("");
  return `${pageIntro("Formas de pagamento", "Cadastre cart\u00f5es para selecionar em qualquer gasto.")}
    <article class="panel"><div class="panel-head"><div><h3>Seus cart\u00f5es</h3><p>O cadastro guarda apenas os quatro \u00faltimos d\u00edgitos. CVV e n\u00famero completo n\u00e3o s\u00e3o armazenados.</p></div><button class="button button-primary" data-new-kind="paymentMethods">+ Cadastrar cart\u00e3o</button></div>
    ${methods.length ? `<div class="table-wrap"><table class="data-table payment-method-table"><thead><tr><th>Nome</th><th>Institui\u00e7\u00e3o financeira</th><th>N\u00famero</th><th>Validade</th><th></th></tr></thead><tbody>${rows}</tbody></table></div>` : `<div class="empty-state"><div class="empty-illustration">&#9635;</div><h3>Nenhum cart\u00e3o cadastrado</h3><p>Cadastre um cart\u00e3o para escolher a origem do pagamento nos abastecimentos, manuten\u00e7\u00f5es, pneus e despesas.</p><button class="button button-primary" data-new-kind="paymentMethods">+ Cadastrar cart\u00e3o</button></div>`}</article>`;
}

const recordConfigs = {
  refuels: { title: "Abastecimentos", desc: "Consumo calculado por intervalos entre tanques cheios.", empty: "Nenhum abastecimento registrado.", columns: [["date", "Data", (row) => formatDate(row.date)], ["fuel", "Combustível", (row) => row.fuel || "—"], ["liters", "Litros", (row) => `${decimal(row.liters, 2)} L`], ["price", "Preço/L", (row) => money(row.pricePerLiter)], ["total", "Total", (row) => money(row.total)], ["paymentMethod", "Pagamento", (row) => row.paymentMethod || "\u2014"], ["odometer", "Quilometragem", (row) => row.odometer ? `${Number(row.odometer).toLocaleString("pt-BR")} km` : "—"], ["consumption", "Consumo", (row, data) => { const interval = fuelSummary(data.refuels).intervals.find((item) => item.to === row.date && item.km === Number(row.odometer) - Number((data.refuels.find((other) => other.date === item.from) || {}).odometer)); return interval ? `${decimal(interval.kmPerLiter)} km/L` : "—"; }]] },
  maintenances: { title: "Manutenções", desc: "Serviços, revisões e alertas de próxima data ou quilometragem.", empty: "Nenhuma manutenção registrada.", columns: [["date", "Data", (row) => formatDate(row.date)], ["service", "Serviço", (row) => row.service || "—"], ["category", "Categoria", (row) => row.category || "—"], ["amount", "Valor", (row) => money(row.amount)], ["paymentMethod", "Pagamento", (row) => row.paymentMethod || "\u2014"], ["odometer", "Km", (row) => row.odometer ? Number(row.odometer).toLocaleString("pt-BR") : "—"], ["next", "Próximo", (row) => row.nextOdometer ? `${Number(row.nextOdometer).toLocaleString("pt-BR")} km` : row.nextDate ? formatDate(row.nextDate) : "—"]] },
  tires: { title: "Pneus", desc: "Compras, consertos e serviços do conjunto de pneus.", empty: "Nenhum serviço de pneus registrado.", columns: [["date", "Data", (row) => formatDate(row.date)], ["action", "Serviço", (row) => row.action || "—"], ["tire", "Pneu", (row) => [row.brand, row.model, row.tireSize].filter(Boolean).join(" · ") || "—"], ["quantity", "Qtd.", (row) => row.quantity || "—"], ["amount", "Valor", (row) => money(row.amount)], ["paymentMethod", "Pagamento", (row) => row.paymentMethod || "\u2014"], ["odometer", "Km", (row) => row.odometer ? Number(row.odometer).toLocaleString("pt-BR") : "—"]] },
  expenses: { title: "Despesas", desc: "Gastos avulsos e despesas vinculadas às viagens.", empty: "Nenhuma despesa registrada.", columns: [["date", "Data", (row) => formatDate(row.date)], ["category", "Categoria", (row) => row.category || "Outros"], ["description", "Descrição", (row) => row.description || "—"], ["city", "Cidade", (row) => row.city || "—"], ["amount", "Valor", (row) => money(row.amount)], ["paymentMethod", "Pagamento", (row) => row.paymentMethod || "\u2014"], ["trip", "Viagem", (row) => row.tripId ? "Vinculada" : "—"]] },
  trips: { title: "Viagens", desc: "Distância e gastos calculados a partir dos registros da viagem.", empty: "Nenhuma viagem registrada.", columns: [["dates", "Período", (row) => row.endDate ? `${formatDate(row.startDate)} – ${formatDate(row.endDate)}` : formatDate(row.startDate)], ["route", "Percurso", (row) => `${row.origin || "—"} → ${row.destination || "—"}`], ["distance", "Distância", (row) => { const value = tripDistance(row); return value == null ? "—" : `${Number(value).toLocaleString("pt-BR")} km`; }], ["purpose", "Finalidade", (row) => row.purpose || "—"], ["expenses", "Gastos", (row, data) => money(data.expenses.filter((expense) => expense.tripId === row.id).reduce((sum, expense) => sum + Number(expense.amount || 0), 0))]] },
};

export function renderRecords(kind, records, data, canEdit, user = null) {
  const config = recordConfigs[kind];
  const columns = kind === "trips"
    ? [...config.columns, ["costPerKm", "Gasto/km", (row, currentData) => {
        const tripExpenses = currentData.expenses.filter((expense) => expense.tripId === row.id);
        const cost = tripExpenses.reduce((sum, expense) => sum + Number(expense.amount || 0), 0);
        const km = tripDistance(row);
        return km > 0 ? `${money(cost / km)}/km` : "Dados insuficientes";
      }]]
    : kind === "tires"
      ? [...config.columns, ["life", "Vida útil aprox.", (row, currentData) => {
          const eligible = ["compra", "troca"].includes(String(row.action || "").toLowerCase());
          if (!eligible || !Number(row.odometer)) return "Dados insuficientes";
          const previous = currentData.tires.filter((item) => item.id !== row.id && ["compra", "troca"].includes(String(item.action || "").toLowerCase()) && Number(item.odometer) < Number(row.odometer) && (!row.tireSize || !item.tireSize || item.tireSize === row.tireSize)).sort((a, b) => Number(b.odometer) - Number(a.odometer))[0];
          return previous ? `${(Number(row.odometer) - Number(previous.odometer)).toLocaleString("pt-BR")} km` : "Aguardando próximo registro";
        }]]
      : config.columns;
  const rows = [...records].sort((a, b) => (b.date || b.startDate || "").localeCompare(a.date || a.startDate || ""));
  const rowsMarkup = rows.map((row) => {
    const mayEditThisRecord = canEdit && (user?.role === "owner" || row.createdBy === user?.uid);
    return `<tr>${columns.map(([, , render]) => `<td>${escapeHtml(render(row, data))}</td>`).join("")}<td><div class="row-actions">${kind === "trips" && canEdit ? `<button class="row-action" title="Adicionar gasto à viagem" data-trip-expense="${escapeHtml(row.id)}">＋</button>` : ""}${mayEditThisRecord ? `<button class="row-action" title="Editar registro" data-edit-path="${escapeHtml(row.path)}" data-edit-kind="${kind}">✎</button><button class="row-action" title="Excluir registro" data-delete-path="${escapeHtml(row.path)}">×</button>` : ""}</div></td></tr>`;
  }).join("");
  return `${pageIntro(config.title, config.desc, canEdit ? `<button class="button button-primary" data-new-kind="${kind}">＋ Novo registro</button>` : "")}
    <article class="panel"><div class="panel-head"><div><h3>${records.length} ${records.length === 1 ? "registro" : "registros"}</h3><p>Exibindo até 250 lançamentos mais recentes.</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr>${columns.map(([, label]) => `<th>${escapeHtml(label)}</th>`).join("")}<th></th></tr></thead><tbody>${rowsMarkup || `<tr><td colspan="${columns.length + 1}"><div class="table-empty"><strong>${escapeHtml(config.empty)}</strong>Os novos registros aparecerão aqui.</div></td></tr>`}</tbody></table></div></article>`;
}

export function renderFinance({ data, period = "month", customStart = "", customEnd = "" }) {
  const events = financialEvents(data);
  const filtered = filterPeriod(events, period, "date", customStart, customEnd);
  const total = filtered.reduce((sum, item) => sum + item.amount, 0);
  const categories = categoryTotals(filtered, "category", "amount");
  const labels = { week: "Esta semana", "last-week": "Semana passada", month: "Este mês", "last-month": "Mês passado", "30-days": "Últimos 30 dias", "12-months": "Últimos 12 meses", year: "Este ano", "last-year": "Ano passado", custom: "Período personalizado", all: "Todo o período" };
  const shown = period === "all" ? events : filtered;
  const paymentTotals = [...shown.reduce((totals, item) => {
    const label = item.paymentMethod || "N\u00e3o informado";
    totals.set(label, (totals.get(label) || 0) + item.amount);
    return totals;
  }, new Map()).entries()].sort((a, b) => b[1] - a[1]);
  const lifetime = getFinanceSummary(data, events);
  const monthlyAverage = events.length ? events.reduce((sum, item) => sum + item.amount, 0) / Math.max(1, new Set(events.map((item) => (item.date || "").slice(0, 7))).size) : 0;
  const spendBy = [
    ["Combustível", shown.filter((item) => item.kind === "refuels").reduce((sum, item) => sum + item.amount, 0)],
    ["Manutenção", shown.filter((item) => item.kind === "maintenances").reduce((sum, item) => sum + item.amount, 0)],
    ["Pneus", shown.filter((item) => item.kind === "tires").reduce((sum, item) => sum + item.amount, 0)],
    ["Viagens e outros", shown.filter((item) => item.kind === "expenses").reduce((sum, item) => sum + item.amount, 0)],
  ];
  return `${pageIntro("Visão financeira", "Acompanhe os gastos deste veículo por período e categoria.", `<div class="toolbar"><select id="finance-period" aria-label="Período">${[["week", "Esta semana"], ["last-week", "Semana passada"], ["month", "Este mês"], ["last-month", "Mês passado"], ["30-days", "Últimos 30 dias"], ["12-months", "Últimos 12 meses"], ["year", "Este ano"], ["last-year", "Ano passado"], ["custom", "Período personalizado"], ["all", "Todo o período"]].map(([key, label]) => `<option value="${key}" ${period === key ? "selected" : ""}>${label}</option>`).join("")}</select><input id="finance-start" type="date" aria-label="Data inicial" value="${escapeHtml(customStart)}" ${period === "custom" ? "" : "hidden"}/><input id="finance-end" type="date" aria-label="Data final" value="${escapeHtml(customEnd)}" ${period === "custom" ? "" : "hidden"}/></div>`)}
    <section class="grid grid-4">${metric("Total · " + labels[period], money(total), `${shown.length} lançamentos`, "↗", true)}${metric("Gasto médio mensal", money(monthlyAverage), "Com base nos meses registrados", "▦")}${metric("Gasto neste ano", money(lifetime.annual), "Lançamentos do ano atual", "▤")}${metric("Custo por km", lifetime.costPerKm == null ? "Dados insuficientes" : `${money(lifetime.costPerKm)}/km`, `${lifetime.kmDriven ? `${lifetime.kmDriven.toLocaleString("pt-BR")} km observados` : "Registre odômetros"}`, "⌁")}</section>
    <section class="grid grid-4" style="margin-top:10px">${metric("Gasto médio semanal", money(lifetime.weeklyAverage), "Com base nos registros carregados", "◷")}${metric("Combustível", money(spendBy[0][1]), "Abastecimentos", "◉")}${metric("Manutenção", money(spendBy[1][1]), "Serviços registrados", "⚙")}${metric("Pneus", money(spendBy[2][1]), "Serviços registrados", "◌")}</section>
    <article class="panel" style="margin-top:15px"><div class="panel-head"><div><h3>Gastos por categoria</h3><p>${escapeHtml(labels[period])}</p></div></div><div class="panel-body"><div class="finance-breakdown">${spendBy.map(([label, value]) => `<div class="finance-category"><span>${escapeHtml(label)}</span><strong>${money(value)}</strong></div>`).join("")}${categories.filter((item) => !["Combustível", "Manutenção", "Pneus"].includes(item.category)).slice(0, 1).map((item) => `<div class="finance-category"><span>${escapeHtml(item.category)}</span><strong>${money(item.value)}</strong></div>`).join("")}</div></div></article>
    <article class="panel" style="margin-top:15px"><div class="panel-head"><div><h3>Gastos por forma de pagamento</h3><p>${escapeHtml(labels[period])}</p></div></div><div class="panel-body"><div class="finance-breakdown">${paymentTotals.map(([label, value]) => `<div class="finance-category"><span>${escapeHtml(label)}</span><strong>${money(value)}</strong></div>`).join("") || `<div class="table-empty">Sem pagamentos neste per\u00edodo.</div>`}</div></div></article>
    <article class="panel" style="margin-top:15px"><div class="panel-head"><div><h3>Lançamentos do período</h3><p>${shown.length} registros · ${escapeHtml(labels[period])}</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Data</th><th>Tipo</th><th>Descrição</th><th>Pagamento</th><th>Km</th><th>Valor</th></tr></thead><tbody>${shown.map((item) => `<tr><td>${formatDate(item.date)}</td><td><span class="tag">${escapeHtml(item.category)}</span></td><td>${escapeHtml(item.detail)}</td><td>${escapeHtml(item.paymentMethod || "\u2014")}</td><td>${item.odometer ? `${Number(item.odometer).toLocaleString("pt-BR")} km` : "—"}</td><td><strong>${money(item.amount)}</strong></td></tr>`).join("") || `<tr><td colspan="6"><div class="table-empty">Sem lançamentos para este período.</div></td></tr>`}</tbody></table></div></article>`;
}

export function renderReports({ vehicle, data, canEdit }) {
  return `${pageIntro("Relatórios", "Escolha o recorte, confira os dados e exporte quando precisar.")}
    <article class="panel"><div class="panel-head"><div><h3>Montar relatório</h3><p>Os dados são processados localmente no navegador.</p></div></div><div class="panel-body"><div class="report-controls"><select id="report-type"><option value="complete">Relatório completo</option><option value="fuel">Abastecimentos e consumo</option><option value="maintenance">Manutenções</option><option value="tires">Pneus</option><option value="expenses">Despesas</option></select><select id="report-period"><option value="all">Todo o período</option><option value="week">Esta semana</option><option value="last-week">Semana passada</option><option value="month">Este mês</option><option value="last-month">Mês passado</option><option value="30-days">Últimos 30 dias</option><option value="12-months">Últimos 12 meses</option><option value="year">Este ano</option><option value="last-year">Ano passado</option><option value="custom">Período personalizado</option></select><input id="report-start" type="date" aria-label="Data inicial" hidden /><input id="report-end" type="date" aria-label="Data final" hidden /><button class="button button-primary" data-report="pdf">Gerar PDF</button><button class="button button-quiet" data-report="print">Imprimir</button><button class="button button-quiet" data-report="csv">Exportar CSV</button><button class="button button-quiet" data-report="json">Backup JSON</button></div><div class="notice-box" style="margin-top:17px">O PDF é gerado nesta sessão do navegador e não é enviado nem salvo no Firebase. O backup JSON inclui apenas o veículo selecionado e os registros carregados.</div></div></article>
    <article class="panel report-sheet" id="report-preview" style="margin-top:15px"><p class="section-kicker">PRÉVIA DO RELATÓRIO</p><h2>${escapeHtml(vehicle?.name || "Veículo")}</h2><p class="report-meta">Resumo dos registros carregados · até 250 por coleção</p><div class="report-stats"><div class="report-stat"><span>Gasto total visível</span><strong>${money(financialEvents(data).reduce((sum, item) => sum + item.amount, 0))}</strong></div><div class="report-stat"><span>Abastecimentos</span><strong>${data.refuels.length}</strong></div><div class="report-stat"><span>Consumo médio</span><strong>${fuelSummary(data.refuels).averageKmPerLiter ? `${decimal(fuelSummary(data.refuels).averageKmPerLiter)} km/L` : "Dados insuficientes"}</strong></div></div><p class="comparison-note">Use os filtros acima para preparar uma exportação. Todos os valores calculados são derivados dos dados cadastrados.</p></article>`;
}

export function renderSharing({ vehicle, shares = [], invites = [], user, canManage }) {
  if (!vehicle) return renderNoVehicle();
  const rows = shares.map((share) => `<div class="share-row"><div class="share-person"><span class="avatar-initial">${escapeHtml((share.displayName || share.email || "U").slice(0, 1).toUpperCase())}</span><div><strong>${escapeHtml(share.displayName || "Usuário")}</strong><span>${escapeHtml(share.email || "")}</span></div></div>${canManage ? `<select class="share-role" data-share-role="${escapeHtml(share.userId)}"><option value="editor" ${share.role === "editor" ? "selected" : ""}>Editor</option><option value="viewer" ${share.role === "viewer" ? "selected" : ""}>Visualizador</option></select>` : `<span class="tag ${share.role === "editor" ? "" : "tag-muted"}">${share.role === "editor" ? "Editor" : "Visualizador"}</span>`}${canManage ? `<div class="row-actions"><button class="button button-quiet" data-remove-share="${escapeHtml(share.userId)}">Remover</button></div>` : ""}</div>`).join("");
  const pendingRows = invites.map((invite) => `<div class="share-row"><div class="share-person"><span class="avatar-initial">…</span><div><strong>Convite pendente</strong><span>${escapeHtml(invite.email)}</span></div></div>${canManage ? `<select class="share-role" data-invite-role="${escapeHtml(invite.email)}"><option value="editor" ${invite.role === "editor" ? "selected" : ""}>Editor</option><option value="viewer" ${invite.role === "viewer" ? "selected" : ""}>Visualizador</option></select>` : `<span class="tag tag-warm">Pendente</span>`}${canManage ? `<div class="row-actions"><button class="button button-quiet" data-remove-invite="${escapeHtml(invite.email)}">Cancelar</button></div>` : ""}</div>`).join("");
  const ownerRow = canManage
    ? `<div class="share-row"><div class="share-person"><span class="avatar-initial">${escapeHtml((user?.displayName || "P").slice(0, 1).toUpperCase())}</span><div><strong>${escapeHtml(user?.displayName || "Proprietário")}</strong><span>${escapeHtml(user?.email || "")}</span></div></div><span class="tag">Proprietário</span><span class="record-subtitle">Acesso total</span></div>`
    : `<div class="share-row"><div class="share-person"><span class="avatar-initial">${escapeHtml((user?.displayName || "U").slice(0, 1).toUpperCase())}</span><div><strong>Você</strong><span>${escapeHtml(user?.email || "")}</span></div></div><span class="tag ${vehicle.role === "editor" ? "" : "tag-muted"}">${vehicle.role === "editor" ? "Editor" : "Visualizador"}</span><span class="record-subtitle">Neste veículo</span></div>`;
  return `${pageIntro("Acesso ao veículo", "Compartilhe os registros deste veículo com alguém de confiança.", "")}
    ${canManage ? `<article class="panel"><div class="panel-head"><div><h3>Convidar alguém</h3><p>O acesso é ativado quando a pessoa entrar com este e-mail Google.</p></div></div><div class="panel-body"><form id="share-form" class="share-invite"><div class="form-field"><label for="share-email">E-mail da conta Google</label><input id="share-email" type="email" required placeholder="nome@exemplo.com" /></div><div class="form-field"><label for="share-role-select">Permissão</label><select id="share-role-select"><option value="viewer">Visualizador · somente leitura</option><option value="editor">Editor · pode registrar e editar</option></select></div><button class="button button-primary" type="submit">Enviar convite</button><p id="share-error" class="form-error" role="alert"></p></form></div></article>` : `<div class="notice-box">Você tem acesso de ${vehicle.role === "editor" ? "editor" : "visualizador"}. Somente o proprietário pode administrar compartilhamentos.</div>`}
    <article class="panel" style="margin-top:15px"><div class="panel-head"><div><h3>${canManage ? "Pessoas com acesso" : "Seu acesso"}</h3><p>${canManage ? `${shares.length + 1} conta(s) com acesso ativo${invites.length ? ` · ${invites.length} convite(s) pendente(s)` : ""}` : "A permissão foi definida pelo proprietário."}</p></div></div><div class="panel-body">${ownerRow}${canManage ? `${rows}${pendingRows || ""}${!rows && !pendingRows ? `<div class="table-empty">Ainda não há outros usuários com acesso.</div>` : ""}` : ""}</div></article>`;
}
